config/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.views import dashboard

admin.site.site_header = "管理系统"
admin.site.site_title = "管理系统"
admin.site.index_title = "欢迎来到管理系统"

urlpatterns = [
    path('__debug__', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', dashboard, name='index'),
    path('dashboard/', dashboard, name='index_view'),
    path('account/', include('account.urls')),
    path('academics/', include('academics.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('result/', include('result.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password/password_reset.html'
         ),
         name="password_reset",
         ),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password/password_reset_done.html'
         ),
         name="password_reset_done",
         ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password/password_reset_confirm.html'
         ),
         name='password_reset_confirm',
         ),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password/password-reset-complete.html'
         ),
         name='password_reset_complete'
         ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='landing'),
    path('admission/', views.online_admission, name='online_admission'),
    path('admission/payment/<int:pk>/', views.online_admission_payment,
         name='online_admission_payment'),
    path('admission/paynow/<int:pk>/', views.payment,
         name='payment'),
]

result/urls.py
from django.urls import path

from . import views
from students.views import student_result_view

app_name = 'result'

urlpatterns = [
    path('<int:student_id>/<int:semester>/', student_result_view, name='show_result'),
    path('details/<int:student_id>/<int:semester>/',
        views.show_result_by_semester, name='result_by_semester'),
    path('upload-subjects-csv/', views.upload_subjects_csv, name='import_subject_csv'),
]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
     path('', views.students_dashboard_index, 
          name='students_dashboard_index'),
     path('all/', views.students_view, name='all_student'),
     path('add/', views.add_student_view, name='add_student'),
     path('add-counsel-data/<int:student_id>/', views.add_counseling_data, 
          name='add_counseling_data'),
     path('admitted-students/', views.admitted_students_list,
          name='admitted_student_list'),
     path('online-applicants/', views.online_applicants_list, 
          name='online_applicants_list'),
     path('online-applicants/<int:pk>/admit/', views.admit_student,
          name='admit_student'),
     path('paid-registrants/', views.paid_registrants, 
          name='paid_registrants'),
     path('update-registrant/<int:pk>/', views.update_online_registrant, 
          name='update_online_registrant'),
     path('update/<int:pk>/', views.student_update_view.as_view(),
          name='update_student'),
     path('<int:pk>/detail/', views.student_detail_view.as_view(),
          name='student_details'),
     path('<int:pk>/delete/', views.student_delete_view, name='delete_student'),
     path('<int:pk>/students/', views.students_by_department_view,
          name='students_by_dept'),
     path('result/', views.student_result_view, name='result'),
     path('add_result_from_student/<int:pk>/', views.add_result_from_student_detail_view, 
          name='add_result_in_details'),
]

students/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import Tab, TabHolder
from crispy_forms.layout import (Layout, Field,
                                ButtonHolder, Submit)
from .models import AdmissionStudent, CounselingComment

class StudentForm(forms.ModelForm):
    class Meta:
        model = AdmissionStudent
        fields = [
            'name',
            'photo',
            'fathers_name',
            'mothers_name',
            'date_of_birth',
            'last_exam_roll',
            'current_address',
            'permanent_address',
            'last_exam_registration',
            'department_choice',
            'mobile_number',
            'email',
            'last_exam_name',
            'last_exam_result'
        ]
        widgets = {
            'date_of_birth': forms.TextInput({'type': 'date'}),
        }


class AdmissionForm(forms.ModelForm):
    class Meta:
        model = AdmissionStudent
        fields = [
            'choosen_department',
        ]


class StudentRegistrantUpdateForm(forms.ModelForm):
    class Meta:
        model = AdmissionStudent
        fields = [
            'name',
            'photo',
            'fathers_name',
            'mothers_name',
            'date_of_birth',
            'last_exam_roll',
            'current_address',
            'permanent_address',
            'last_exam_registration',
            'mobile_number',
            'email',
            'last_exam_name',
            'last_exam_result',
            'choosen_department',
        ]
        widgets = {
            'date_of_birth': forms.TextInput({'type': 'date'}),
        }


class CounselingDataForm(forms.ModelForm):
    class Meta:
        model = CounselingComment
        fields = ['comment', 'counselor']

result/views.py
import csv, io
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test

from academics.views import user_is_staff
from academics.models import Semester
from students.models import Student,StudentBase
from result.models import Result, StudentInfo


@user_passes_test(user_is_staff)
def show_result_by_semester(request, student_id, semester):
    student = Student.objects.get(pk=student_id)
    semester = Semester.objects.get(number=semester)
    results = Result.objects.filter(student_id=student_id,
                                    semester=semester)
    context = {'results': results, 'student': student}
    return render(request, 'students/result_in_detail.html', context)



@user_passes_test(user_is_staff)
def upload_subjects_csv(request):
    if request.user.has_perm('create_stuff'):
        template = 'result/add_subject_csv.html'
        prompt = {
            'order': '学生姓名, 学生学号，学生专业'
        }
        if request.method == 'GET':
            return render(request, template, prompt)
        
        csv_file = request.FILES['file']
        if not csv_file.name.endswith('.csv'):
            messages.error(request, '请上传CSV格式的文件')
        try:
            data_set = csv_file.read().decode('UTF-8')
            io_string = io.StringIO(data_set)
            next(io_string)
            # TODO: upload data for foreignkey also, and
            # create object for foreignkey if no data found.
            for column in csv.reader(io_string, delimiter=',', quotechar='|'):
                _, created = Student.objects.update_or_create(
                    name=column[0],
                    registration_number=column[1],
                    department=column[2],
                )
        except:
            pass
        context = {}
        return render(request, template, context)
    else:
        return render(request, 'admin_tools/permission_required.html')

students/views.py
from datetime import date

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.views.generic import DetailView, UpdateView
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from academics.views import user_is_staff
from academics.models import Department, Semester
from result.models import Result, StudentInfo
from .models import Student, AdmissionStudent, CounselingComment
from .forms import (StudentForm, AdmissionForm, 
    StudentRegistrantUpdateForm, CounselingDataForm)


@user_passes_test(user_is_staff)
def students_dashboard_index(request):
    """
    Dashboard for online admission system. 
    """
    online_applicants = AdmissionStudent.objects.filter(admitted=False)
    admitted_students = AdmissionStudent.objects.filter(admitted=True)
    paid_registrants = online_applicants.filter(paid=True)
    context = {
        'online_applicants': online_applicants,
        'admitted_students': admitted_students,
        'paid_registrants': paid_registrants,
    }
    return render(request, 'students/dashboard_index.html', context)


@user_passes_test(user_is_staff)
def online_applicants_list(request):
    """
    Returns template with list of applicant students 
    who aren't admitted yet. 
    """
    online_applicants = AdmissionStudent.objects.filter(admitted=False)
    context = {
        'online_applicants': online_applicants,
    }
    return render(request, 'students/dashboard_online_applicants.html', context)


@user_passes_test(user_is_staff)
def admitted_students_list(request):
    """ 
    Returns list of students admitted from online registration.
    """
    admitted_students = AdmissionStudent.objects.filter(admitted=True)
    context = {
        'admitted_students': admitted_students,
    }
    return render(request, 'students/dashboard_admitted_students.html', context)


@user_passes_test(user_is_staff)
def paid_registrants(request):
    """ 
    Returns list of students already paid from online registration.
    """
    paid_students = AdmissionStudent.objects.filter(paid=True)
    context = {
        'paid_students': paid_students,
    }
    return render(request, 'students/dashboard_paid_students.html', context)


@user_passes_test(user_is_staff)
def admit_student(request, pk):
    """ 
    Admit applicant found by id/pk into choosen department 
    """
    applicant = get_object_or_404(AdmissionStudent, pk=pk)
    if request.method == 'POST':
        form = AdmissionForm(request.POST, instance=applicant)
        if form.is_valid():
            student = form.save(commit=False)
            student.admitted = True
            student.admission_date = date.today()
            student.save()
            return redirect('students:admitted_student_list')
    else:
        form = AdmissionForm()
        context = {'form': form, 'applicant': applicant}
    return render(request, 'students/dashboard_admit_student.html', context)


@user_passes_test(user_is_staff)
def update_online_registrant(request, pk):
    """ 
    Update applicants details, counseling information
    """
    applicant = get_object_or_404(AdmissionStudent, pk=pk)
    counseling_records = CounselingComment.objects.filter(registrant_student=applicant)
    if request.method == 'POST':
        form = StudentRegistrantUpdateForm(
            request.POST, 
            request.FILES, 
            instance=applicant)
        if form.is_valid():
            form.save()
            return redirect('students:online_applicants_list')
    else:
        form = StudentRegistrantUpdateForm(instance=applicant)
        counseling_form = CounselingDataForm()
        context = {
            'form': form, 
            'applicant': applicant, 
            'counseling_records': counseling_records,
            'counseling_form': counseling_form}
    return render(request, 'students/dashboard_update_online_applicant.html', context)


@user_passes_test(user_is_staff)
def add_counseling_data(request, student_id):
    registrant = get_object_or_404(AdmissionStudent, id=student_id)
    if request.method == 'POST':
        form = CounselingDataForm(request.POST)
        if form.is_valid():
            counseling_comment = form.save(commit=False)
            # TODO: NEEDS IMPROVEMENT
            # counseling_comment.counselor = "SHOULD BE A USER/COUNSELOR"
            counseling_comment.registrant_student = registrant
            counseling_comment.save()
            return redirect('students:update_online_registrant', pk=student_id)

@user_passes_test(user_is_staff)
def student_result_view(request):
    if request.method == 'POST':
        student_id = request.POST.get('student_id')
        semester = request.POST.get('semester')
        student = Student.objects.get(roll=student_id)
        res_semester = Semester.objects.get(number=semester)
        results = Result.objects.filter(student=student, semester=res_semester)
        ctx = {
            'semester': res_semester,
            'results': results,
            'student': student,
        }
        return render(request, 'students/result.html', ctx)
    else:
        return render(request, 'students/result.html')


@user_passes_test(user_is_staff)
def add_student_view(request):
    """
    :param request:
    :return: admission form to
    logged in user.
    """
    if request.method == 'POST':
        form = StudentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            pk = form.instance.pk
            return redirect('students:student_details', pk=pk)
    else:
        form = StudentForm()
    context = {'form': form}
    return render(request, 'students/addstudent.html', context)


@user_passes_test(user_is_staff)
def students_view(request):
    """
    :param request:
    :return: renders student list with all department
    and semesters list.
    """
    all_students = Student.objects.select_related(
        'department', 'semester', 'ac_session').all()
    departments = Department.objects.select_related(
        'head').all()
    context = {'students': all_students,
                'departments': departments,
                }
    return render(request, 'students/students_list.html', context)


@user_passes_test(user_is_staff)
def students_by_department_view(request, pk):
    dept_name = Department.objects.get(pk=pk)
    students = Student.objects.select_related(
        'department', 'semester', 'ac_session').filter(department=dept_name)
    context = {'students': students,}
    return render(request, 'students/students_by_department.html', context)


class student_update_view(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    renders a student update form to update students details.
    """
    model = Student
    fields = ['photo', 'semester', 'mobile',
                'guardian_mobile', 'email']
    template_name = 'students/update_student.html'

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect('account:home')
        return redirect('account:login')

    def get_success_url(self):
        student_id = self.kwargs['pk']
        return reverse_lazy('students:student_details', kwargs={'pk': student_id})


class student_detail_view(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Student
    template_name = 'students/student_details.html'

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect('account:home')
        return redirect('account:login')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        obj = kwargs['object']
        pk = obj.id
        student = Student.objects.get(pk=pk)
        # get student object
        # for showing subjects in option form
        try:
            student_subject_qs = student.has_subjects()[0]
            student_subject_qs = student_subject_qs.subjects.all()
            context['subjects'] = student_subject_qs
        except IndexError:
            context['subjects'] = None
        # getting result objects
        semesters = range(1, student.semester.number + 1)
        context['semesters'] = semesters
        return context


@user_passes_test(user_is_staff)
def student_delete_view(request, pk):
    student = Student.objects.get(pk=pk)
    student.delete()
    return redirect('students:all_student')


@user_passes_test(user_is_staff)
def add_result_from_student_detail_view(request, pk):
    student = Student.objects.get(id=pk)
    if request.method == 'POST':
        subject = request.POST.get('subject')
        subject = StudentInfo.objects.get(subject_code=int(subject))
        marks = request.POST.get('marks')
        semester = student.semester
        try:
            result = Result(
                subject=subject,
                marks=marks,
                semester=semester,
                student=student)
            result.save()
        except IntegrityError:
            return HttpResponse('记录已存在！')

        return redirect('students:student_details', pk=pk)

templates/students/addstudent.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block extra_header %}
{% endblock %}

{% block dashboard-body %}
<form action="." method="POST" class="admission-form d-block" enctype='multipart/form-data'>
  <div class="alert alert-warning">
    <p>先填写必须项，然后点击<em>提交学生信息</em></p>
  </div>
  {% csrf_token %}
  {% crispy form %}
  <input type="submit" value="提交" class="btn btn-dark">
</form>
{% endblock %}

{% block extrajs %}
  <script>
    // Select image
    $('input[type="file"]').change(function(e){
      const fileName = e.target.files[0].name;
      $('.custom-file-label').html(fileName);
    });
  </script>
{% endblock %}

templates/students/dashboard_index.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block extra_header %}
{% endblock %}

{% block dashboard-body %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="#">Students</a></li>
        <li class="breadcrumb-item active" aria-current="page">Index</li>
    </ol>
</nav>

<!-- Stats - Links -->
<div class="row">
    <!-- Topbar Informations -->
    <div class="col-sm-12 col-md-3">
        <div class="card bg-primary p-3">
            <h5>
                <a class="text-light" 
                    href="{% url 'students:online_applicants_list' %}">
                    Online Applicants
                    <span class="badge badge-light">
                        {{ online_applicants.count }}
                    </span>
                </a>
            </h5>
        </div>
    </div>
    <div class="col-sm-12 col-md-3">
        <div class="card bg-info p-3">
            <h5>
                <a class="text-light" href="{% url 'students:admitted_student_list' %}">
                    Admitted <span class="badge badge-light">
                        {{ admitted_students.count }}
                    </span>
                </a>
            </h5>
        </div>
    </div>
    <div class="col-sm-12 col-md-3">
        <div class="card bg-success p-3">
            <h5>
                <a class="text-light" href="{% url 'students:paid_registrants' %}">
                    PAID REGISTRANTS
                    {% if paid_registrants.count > 0 %}
                    <span class="badge badge-light">
                        {{ paid_registrants.count }}
                    </span>
                    {% endif %}
                </a>
            </h5>
        </div>
    </div>
    <div class="col-sm-12 col-md-3">
        <div class="card bg-info p-3">
            <h5>
                <a class="text-light" href="{% url 'pages:online_admission' %}" target="_blank">
                    ADMISSION SITE
                </a>
            </h5>
        </div>
    </div>
</div>
<hr>
<!-- Actions -->
<div class="row">
    <div class="col-12 d-flex">
        <div class="action-btn-box mr-1">
            <a href="{% url 'students:add_student' %}" class="btn btn-sm btn-success">Add New Student</a>
        </div>
        <div class="action-btn-box mr-1">
            <a href="" class="btn btn-info btn-sm">This Months Admissons</a>
        </div>
        <div class="action-btn-box mr-1">
            <a href="" class="btn btn-sm btn-dark">
                Extract data from admitted students
            </a>
        </div>
        <div class="action-btn-box mr-1">
            <a href="" class="btn btn-sm btn-danger">
                Extract data from registrants
            </a>
        </div>
    </div>
</div>
{% endblock %}

{% block extrajs %}
    <script>
    // Select Image
    $('input[type="file"]').change(function(e){
        const fileName = e.target.files[0].name;
        $('.custom-file-label').html(fileName);
    });
    </script>
{% endblock %}

templates/students/dashboard_online_applicants.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block extra_header %}
{% endblock %}

{% block dashboard-body %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item">
            <a href="{% url 'students:students_dashboard_index' %}">Students</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Online Applicants</li>
    </ol>
</nav>

<!-- Online Applicants Table Row -->
<div class="container-fluid">
    <div class="row">
        <div class="col-12 pl-0">
            <h4 class="ml-0">Online Admission Registrants</h4>
        </div>
        <!-- Online Applicants Table -->
        <div id="online-applicants" class="mt-4">
            <table class="table table-bordered table-hover">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Image</th>
                        <th scope="col">Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">Department Choice</th>
                        <th scope="col">Application Date</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="bg-light">
                
                    {% for applicant in online_applicants %}
                    <tr>
                        <th scope="row">{{ applicant.id }}</th>
                        <td>
                            <img src="{{ applicant.photo.url }}" width="50" height="50">
                        </td>
                        <td>{{ applicant.name }}</td>
                        <td>{{ applicant.permanent_address }}</td>
                        <td>{{ applicant.department_choice }}</td>
                        <td>{{ applicant.created }}</td>
                        <td>
                            <a href="" class="btn btn-sm btn-primary">More</a>
                            <a href="{% url 'students:admit_student' pk=applicant.id %}" class="btn btn-sm btn-success">
                                Admission
                            </a>
                            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}"
                                class="btn btn-sm btn-info">
                                Update
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/students/dashboard_paid_students.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block extra_header %}
{% endblock %}

{% block dashboard-body %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
        <li class="breadcrumb-item">
            <a href="{% url 'students:students_dashboard_index' %}">Students</a>
        </li>
        <li class="breadcrumb-item active" aria-current="page">Paid Applicants</li>
    </ol>
</nav>

<!-- Online Applicants Table Row -->
<div class="container-fluid">
    <div class="row">
        <div class="col-12 pl-0">
            <h4 class="ml-0">Online Admission Registrants</h4>
        </div>
        <!-- Online Applicants Table -->
        <div id="online-applicants" class="mt-4">
            <table class="table table-bordered table-hover">
                <thead class="thead-light">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Image</th>
                        <th scope="col">Name</th>
                        <th scope="col">Address</th>
                        <th scope="col">Department Choice</th>
                        <th scope="col">Application Date</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody class="bg-light">
                
                    {% for applicant in paid_students %}
                    <tr>
                        <th scope="row">{{ applicant.id }}</th>
                        <td>
                            <img src="{{ applicant.photo.url }}" width="50" height="50">
                        </td>
                        <td>{{ applicant.name }}</td>
                        <td>{{ applicant.permanent_address }}</td>
                        <td>{{ applicant.department_choice }}</td>
                        <td>{{ applicant.created }}</td>
                        <td>
                            <a href="" class="btn btn-sm btn-primary">More</a>
                            <a href="{% url 'students:admit_student' pk=applicant.id %}" class="btn btn-sm btn-success">
                                Admission
                            </a>
                            <a href="{% url 'students:update_online_registrant' pk=applicant.id %}"
                                class="btn btn-sm btn-info">
                                Update
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/students/student_details.html
{% extends 'layout.html' %}
{% load static %}
{% load student_tags %}

{% block content %}
<section id="student-detail-section header">
  <div id="student-detail-section--inner">
    <div class="container">
      <a href="{% url 'index_view' %}" class="btn btn-danger">
        Dashboard
      </a>
      <a href="{% url 'students:delete_student' pk=student.pk %}" class="btn btn-danger">
        <i class="fas fa-trash-alt"></i>
      </a>
      <a href="{% url 'students:update_student' pk=student.id %}" class="btn btn-secondary">
        <i class="fas fa-edit"></i>
      </a>
      <div class="row py-5">
        <div class="col-3">
          <img class="student-profile-img" src="{{ student.photo.url }}" alt="" width="200" height="200">
        </div>
        <div class="col-8">
          <h2>{{ student.name }}</h2>
          <h4>{{ student.department }} {{ student.semester }}</h4>
          <h4>Session: {{ student.ac_session }}</h4>
          {% if student.mobile %}
            <h4>Mobile: {{ student.mobile }}</h4>
          {% endif %}
          {% if student.email %}
          <h4>Mail: {{ student.email }}</h4>
          {% endif %}
          {% if student.guardian_mobile %}
            <h4>Guardian: {{ student.guardian_mobile }}</h4>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</section>

<section class="mt-5" id="student-information">
  <div class="container">
    <div class="row">
      <div class="col-3">
        <h3>Result(s):</h3>
        
        <!-- Result Form Modal -->
        <div class="modal fade" id="resultForm" tabindex="-1">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Result For:</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <form action="{% url 'students:add_result_in_details' pk=student.id %}" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="marks">Marks</label>
                    <input type="number" class="form-control" name="marks" id="marks">
                  </div>
                  <div class="form-group">
                    <label for="subject">Subject</label>
                    <select class="form-control" id="subject" name="subject">
                      {% for sub in subjects %}
                        <option value="{{ sub.subject_code }}">{{ sub.name }}</option>
                      {% endfor %}
                    </select>                    
                  </div>
                  <input type="submit" value="Save">
                </form>
              </div>
            </div>
          </div>
        </div>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">
                <button type="button" class="btn btn-sm btn-success btn-block" data-toggle="modal" data-target="#resultForm">
                  <i class="fas fa-plus"></i> Add New Record
                </button>
              </th>
            </tr>
          </thead>
          <tbody>
            {% for semester in semesters %}
              <tr>
                <td>
                  <a href="{% url 'result:result_by_semester' student_id=student.id semester=semester %}">
                  {{ semester|num_suffix }} Semester</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="col-4">
        <h3>Attendance:</h3>
        <a href="" class="btn btn-sm btn-success">
          <i class="fas fa-plus"></i> Add New Record
        </a>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Semester</th>
              <th scope="col">Avg.</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Otto</td>
              <td>@mdo</td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-4">
        <h3>Academic Report(s):</h3>
        <a href="" class="btn btn-sm btn-success">
          <i class="fas fa-plus"></i> Add New Record
        </a>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th scope="col">Semester</th>
              <th scope="col">Refference</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Mark</td>
              <td>Otto</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div> <!-- end of row -->
  </div>
</section>
{% endblock %}