config/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.views import dashboard

admin.site.site_header = "管理系统"
admin.site.site_title = "管理系统"
admin.site.index_title = "欢迎来到管理系统"

urlpatterns = [
    path('__debug__', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', dashboard, name='index'),
    path('dashboard/', dashboard, name='index_view'),
    path('account/', include('account.urls')),
    path('academics/', include('academics.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('result/', include('result.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password/password_reset.html'
         ),
         name="password_reset",
         ),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password/password_reset_done.html'
         ),
         name="password_reset_done",
         ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password/password_reset_confirm.html'
         ),
         name='password_reset_confirm',
         ),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password/password-reset-complete.html'
         ),
         name='password_reset_complete'
         ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='landing'),
    path('admission/', views.online_admission, name='online_admission'),
    path('admission/payment/<int:pk>/', views.online_admission_payment,
         name='online_admission_payment'),
    path('admission/paynow/<int:pk>/', views.payment,
         name='payment'),
]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
     path('', views.students_dashboard_index, 
          name='students_dashboard_index'),
     path('all/', views.students_view, name='all_student'),
     path('add/', views.add_student_view, name='add_student'),
     path('add-counsel-data/<int:student_id>/', views.add_counseling_data, 
          name='add_counseling_data'),
     path('admitted-students/', views.admitted_students_list,
          name='admitted_student_list'),
     path('online-applicants/', views.online_applicants_list, 
          name='online_applicants_list'),
     path('online-applicants/<int:pk>/admit/', views.admit_student,
          name='admit_student'),
     path('paid-registrants/', views.paid_registrants, 
          name='paid_registrants'),
     path('update-registrant/<int:pk>/', views.update_online_registrant, 
          name='update_online_registrant'),
     path('update/<int:pk>/', views.student_update_view.as_view(),
          name='update_student'),
     path('<int:pk>/detail/', views.student_detail_view.as_view(),
          name='student_details'),
     path('<int:pk>/delete/', views.student_delete_view, name='delete_student'),
     path('<int:pk>/students/', views.students_by_department_view,
          name='students_by_dept'),
     path('result/', views.student_result_view, name='result'),
     path('add_result_from_student/<int:pk>/', views.add_result_from_student_detail_view, 
          name='add_result_in_details'),
]

students/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.bootstrap import Tab, TabHolder
from crispy_forms.layout import (Layout, Field,
                                ButtonHolder, Submit)
from .models import AdmissionStudent, CounselingComment

class StudentForm(forms.ModelForm):
    class Meta:
        model = AdmissionStudent
        fields = [
            'name',
            'photo',
            'fathers_name',
            'mothers_name',
            'date_of_birth',
            'last_exam_roll',
            'current_address',
            'permanent_address',
            'last_exam_registration',
            'department_choice',
            'mobile_number',
            'email',
            'last_exam_name',
            'last_exam_result'
        ]
        widgets = {
            'date_of_birth': forms.TextInput({'type': 'date'}),
        }


class AdmissionForm(forms.ModelForm):
    class Meta:
        model = AdmissionStudent
        fields = [
            'choosen_department',
        ]


class StudentRegistrantUpdateForm(forms.ModelForm):
    class Meta:
        model = AdmissionStudent
        fields = [
            'name',
            'photo',
            'fathers_name',
            'mothers_name',
            'date_of_birth',
            'last_exam_roll',
            'current_address',
            'permanent_address',
            'last_exam_registration',
            'mobile_number',
            'email',
            'last_exam_name',
            'last_exam_result',
            'choosen_department',
        ]
        widgets = {
            'date_of_birth': forms.TextInput({'type': 'date'}),
        }


class CounselingDataForm(forms.ModelForm):
    class Meta:
        model = CounselingComment
        fields = ['comment', 'counselor']

students/views.py
from datetime import date

from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.views.generic import DetailView, UpdateView
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from academics.views import user_is_staff
from academics.models import Department, Semester
from result.models import Result, StudentInfo
from .models import Student, AdmissionStudent, CounselingComment
from .forms import (StudentForm, AdmissionForm, 
    StudentRegistrantUpdateForm, CounselingDataForm)


@user_passes_test(user_is_staff)
def students_dashboard_index(request):
    """
    Dashboard for online admission system. 
    """
    online_applicants = AdmissionStudent.objects.filter(admitted=False)
    admitted_students = AdmissionStudent.objects.filter(admitted=True)
    paid_registrants = online_applicants.filter(paid=True)
    context = {
        'online_applicants': online_applicants,
        'admitted_students': admitted_students,
        'paid_registrants': paid_registrants,
    }
    return render(request, 'students/dashboard_index.html', context)


@user_passes_test(user_is_staff)
def online_applicants_list(request):
    """
    Returns template with list of applicant students 
    who aren't admitted yet. 
    """
    online_applicants = AdmissionStudent.objects.filter(admitted=False)
    context = {
        'online_applicants': online_applicants,
    }
    return render(request, 'students/dashboard_online_applicants.html', context)


@user_passes_test(user_is_staff)
def admitted_students_list(request):
    """ 
    Returns list of students admitted from online registration.
    """
    admitted_students = AdmissionStudent.objects.filter(admitted=True)
    context = {
        'admitted_students': admitted_students,
    }
    return render(request, 'students/dashboard_admitted_students.html', context)


@user_passes_test(user_is_staff)
def paid_registrants(request):
    """ 
    Returns list of students already paid from online registration.
    """
    paid_students = AdmissionStudent.objects.filter(paid=True)
    context = {
        'paid_students': paid_students,
    }
    return render(request, 'students/dashboard_paid_students.html', context)


@user_passes_test(user_is_staff)
def admit_student(request, pk):
    """ 
    Admit applicant found by id/pk into choosen department 
    """
    applicant = get_object_or_404(AdmissionStudent, pk=pk)
    if request.method == 'POST':
        form = AdmissionForm(request.POST, instance=applicant)
        if form.is_valid():
            student = form.save(commit=False)
            student.admitted = True
            student.admission_date = date.today()
            student.save()
            return redirect('students:admitted_student_list')
    else:
        form = AdmissionForm()
        context = {'form': form, 'applicant': applicant}
    return render(request, 'students/dashboard_admit_student.html', context)


@user_passes_test(user_is_staff)
def update_online_registrant(request, pk):
    """ 
    Update applicants details, counseling information
    """
    applicant = get_object_or_404(AdmissionStudent, pk=pk)
    counseling_records = CounselingComment.objects.filter(registrant_student=applicant)
    if request.method == 'POST':
        form = StudentRegistrantUpdateForm(
            request.POST, 
            request.FILES, 
            instance=applicant)
        if form.is_valid():
            form.save()
            return redirect('students:online_applicants_list')
    else:
        form = StudentRegistrantUpdateForm(instance=applicant)
        counseling_form = CounselingDataForm()
        context = {
            'form': form, 
            'applicant': applicant, 
            'counseling_records': counseling_records,
            'counseling_form': counseling_form}
    return render(request, 'students/dashboard_update_online_applicant.html', context)


@user_passes_test(user_is_staff)
def add_counseling_data(request, student_id):
    registrant = get_object_or_404(AdmissionStudent, id=student_id)
    if request.method == 'POST':
        form = CounselingDataForm(request.POST)
        if form.is_valid():
            counseling_comment = form.save(commit=False)
            # TODO: NEEDS IMPROVEMENT
            # counseling_comment.counselor = "SHOULD BE A USER/COUNSELOR"
            counseling_comment.registrant_student = registrant
            counseling_comment.save()
            return redirect('students:update_online_registrant', pk=student_id)

@user_passes_test(user_is_staff)
def student_result_view(request):
    if request.method == 'POST':
        student_id = request.POST.get('student_id')
        semester = request.POST.get('semester')
        student = Student.objects.get(roll=student_id)
        res_semester = Semester.objects.get(number=semester)
        results = Result.objects.filter(student=student, semester=res_semester)
        ctx = {
            'semester': res_semester,
            'results': results,
            'student': student,
        }
        return render(request, 'students/result.html', ctx)
    else:
        return render(request, 'students/result.html')


@user_passes_test(user_is_staff)
def add_student_view(request):
    """
    :param request:
    :return: admission form to
    logged in user.
    """
    if request.method == 'POST':
        form = StudentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            pk = form.instance.pk
            return redirect('students:student_details', pk=pk)
    else:
        form = StudentForm()
    context = {'form': form}
    return render(request, 'students/addstudent.html', context)


@user_passes_test(user_is_staff)
def students_view(request):
    """
    :param request:
    :return: renders student list with all department
    and semesters list.
    """
    all_students = Student.objects.select_related(
        'department', 'semester', 'ac_session').all()
    departments = Department.objects.select_related(
        'head').all()
    context = {'students': all_students,
                'departments': departments,
                }
    return render(request, 'students/students_list.html', context)


@user_passes_test(user_is_staff)
def students_by_department_view(request, pk):
    dept_name = Department.objects.get(pk=pk)
    students = Student.objects.select_related(
        'department', 'semester', 'ac_session').filter(department=dept_name)
    context = {'students': students,}
    return render(request, 'students/students_by_department.html', context)


class student_update_view(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    renders a student update form to update students details.
    """
    model = Student
    fields = ['photo', 'semester', 'mobile',
                'guardian_mobile', 'email']
    template_name = 'students/update_student.html'

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect('account:home')
        return redirect('account:login')

    def get_success_url(self):
        student_id = self.kwargs['pk']
        return reverse_lazy('students:student_details', kwargs={'pk': student_id})


class student_detail_view(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    model = Student
    template_name = 'students/student_details.html'

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        if self.request.user.is_authenticated:
            return redirect('account:home')
        return redirect('account:login')

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        obj = kwargs['object']
        pk = obj.id
        student = Student.objects.get(pk=pk)
        # get student object
        # for showing subjects in option form
        try:
            student_subject_qs = student.has_subjects()[0]
            student_subject_qs = student_subject_qs.subjects.all()
            context['subjects'] = student_subject_qs
        except IndexError:
            context['subjects'] = None
        # getting result objects
        semesters = range(1, student.semester.number + 1)
        context['semesters'] = semesters
        return context


@user_passes_test(user_is_staff)
def student_delete_view(request, pk):
    student = Student.objects.get(pk=pk)
    student.delete()
    return redirect('students:all_student')


@user_passes_test(user_is_staff)
def add_result_from_student_detail_view(request, pk):
    student = Student.objects.get(id=pk)
    if request.method == 'POST':
        subject = request.POST.get('subject')
        subject = StudentInfo.objects.get(subject_code=int(subject))
        marks = request.POST.get('marks')
        semester = student.semester
        try:
            result = Result(
                subject=subject,
                marks=marks,
                semester=semester,
                student=student)
            result.save()
        except IntegrityError:
            return HttpResponse('记录已存在！')

        return redirect('students:student_details', pk=pk)

templates/pages/students/admission.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Online Admission at SMSLIO</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div id="admission-header" class="bg-primary text-light py-5 text-center">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Admission Form Form SMS-LIO</h2>
                    <p>Please Fillout the form with proper information. We'll contact you shortly.</p>
                </div>
            </div>
        </div>
    </div>
    <div id="admission-form-main">
        <div class="container">
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <form action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input type="submit" value="Submit" class="btn btn-success">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script>
        // Select image
        $('input[type="file"]').change(function(e){
            const fileName = e.target.files[0].name;
            $('.custom-file-label').html(fileName);
        });
    </script>
</body>
</html>

templates/pages/students/admission_payment.html
{% extends 'layout.html' %}


{% block headrefs %}
    <script src="https://js.braintreegateway.com/web/dropin/1.18.0/js/dropin.min.js"></script>
{% endblock headrefs %}



{% block content %}
<div class="bg-primary text-light py-5 text-center">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 id="header-text">Pay $100 as Admission Fee</h2>
            </div>
        </div>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-6">
        <form autocomplete="off">
            {% if braintree_error %}
                <div class="alert alert-danger fade in">
                    <button class="close" data-dismiss="alert">&times;</button>
                    {{ braintree_error|safe }}
                </div>
            {% endif %}
            <div class="braintree-notifications"></div>
            <div id="braintree-dropin"></div>
            <input style="background-color: #0783ca" id="submit-button" class="btn btn-success btn-lg btn-block" type="button" value="Pay now!" />
        </form>
    </div>
</div>
{% endblock content %}


{% block extrajs %}
<script>
    var braintree_client_token = "{{ braintree_client_token }}";
    var button = document.querySelector('#submit-button');
    const headerText = document.querySelector('#header-text');

    braintree.dropin.create({
        authorization: braintree_client_token,
        container: '#braintree-dropin',
        card: {
            cardholderName: {
                required: false
            }
        }
    }, function (createErr, instance) {
        button.addEventListener('click', function () {
            instance.requestPaymentMethod(function (err, payload) {
                $.ajax({
                    type: 'POST',
                    url: '{% url "pages:payment" pk=registrant.id %}',
                    data: {'paymentMethodNonce': payload.nonce,
                            'csrfmiddlewaretoken':  '{{ csrf_token }}'}
                }).done(function (result) {
                    //do accordingly
                    button.style.display = 'none';
                    headerText.textContent = 'We got your payment, we\'ll contact you soon'
                });
            });
        });
    });
</script>
{% endblock extrajs %}
    