academics/urls.py
from django.urls import path
from . import views
from account.views import AccountListView


app_name = 'academics'

urlpatterns = [
    # Semester
    path('semesters/', views.semesters, name='all_semester'),
    path('departments/', views.departments, name='departments'),
    path('depts/delete/<int:pk>/', views.delete_department, name='delete_dept'),
    path('academic_sessions/', views.academic_session, name='academic_sessions'),
    path('add_user/', views.add_user_view, name='add_user'),
    path('accounts/', AccountListView.as_view(), name='all_accounts'),
    path('department/update/<int:pk>/', views.UpdateDepartment.as_view(),
        name='update_department'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.views import dashboard

admin.site.site_header = "管理系统"
admin.site.site_title = "管理系统"
admin.site.index_title = "欢迎来到管理系统"

urlpatterns = [
    path('__debug__', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', dashboard, name='index'),
    path('dashboard/', dashboard, name='index_view'),
    path('account/', include('account.urls')),
    path('academics/', include('academics.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('result/', include('result.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password/password_reset.html'
         ),
         name="password_reset",
         ),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password/password_reset_done.html'
         ),
         name="password_reset_done",
         ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password/password_reset_confirm.html'
         ),
         name='password_reset_confirm',
         ),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password/password-reset-complete.html'
         ),
         name='password_reset_complete'
         ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='landing'),
    path('admission/', views.online_admission, name='online_admission'),
    path('admission/payment/<int:pk>/', views.online_admission_payment,
         name='online_admission_payment'),
    path('admission/paynow/<int:pk>/', views.payment,
         name='payment'),
]

academics/models.py
from django.db import models
from django.conf import settings
from model_utils.models import TimeStampedModel
from teachers.models import Teacher


class Department(TimeStampedModel):
    name = models.CharField(max_length=255, unique=True)
    short_name = models.CharField('Department Short Form', 
        max_length=5)
    code = models.PositiveIntegerField()
    head = models.ForeignKey(
        Teacher, on_delete=models.CASCADE, blank=True, null=True)
    establish_date = models.DateField(auto_now_add=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.DO_NOTHING, null=True)

    def dept_code(self):
        if not self.code:
            return ""
        return self.code

    def __str__(self):
        return str(self.name)


class AcademicSession(TimeStampedModel):
    year = models.PositiveIntegerField(unique=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.DO_NOTHING, null=True)

    def __str__(self):
        return '{} - {}'.format(self.year, self.year + 1)


class Semester(TimeStampedModel):
    number = models.PositiveIntegerField(unique=True)
    guide = models.ForeignKey(
        Teacher, on_delete=models.CASCADE, default=None, null=True, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.DO_NOTHING, null=True)

    class Meta:
        ordering = ['number', ]

    def __str__(self):
        if self.number == 1:
            return '1st'
        if self.number == 2:
            return '2nd'
        if self.number == 3:
            return '3rd'
        if 3 < self.number <= 12:
            return '%sth' % self.number

academics/forms.py
from django.forms import ModelForm

from .models import Department, Semester, AcademicSession


class DepartmentForm(ModelForm):
    class Meta:
        model = Department
        fields = '__all__'
        exclude = ['created_by', ]


class SemesterForm(ModelForm):
    class Meta:
        model = Semester
        fields = '__all__'
        exclude = ['created_by', ]


class AcademicSessionForm(ModelForm):
    class Meta:
        model = AcademicSession
        fields = '__all__'
        exclude = ['created_by', ]

academics/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from rolepermissions.roles import assign_role

from .models import Semester, Department, AcademicSession
from .forms import SemesterForm, DepartmentForm, AcademicSessionForm
from account.forms import UserRegistrationForm


def user_is_staff(user):
    return user.is_staff

@login_required
def add_user_view(request):
    if request.user.has_perm('create_stuff'):
        if request.method == 'POST':
            user_form = UserRegistrationForm(request.POST)
            if user_form.is_valid():
                role = request.POST.get('user_role')
                if role == 'admin':
                    user = user_form.save()
                    assign_role(user, 'admin')
                    return redirect('academics:all_accounts')
                elif role == 'stuff':
                    user = user_form.save()
                    assign_role(user, 'stuff')
                    return redirect('academics:all_accounts')
            else:
                return render(request, 'academics/add_user.html')
        else:
            user_form = UserRegistrationForm()
        context = {
            'user_form': user_form,
        }
        return render(request, 'academics/add_user.html', context)
    else:
        return render(request, 'academics/permission_required.html')


@user_passes_test(user_is_staff)
def semesters(request):
    '''
    Shows semester list and 
    contains semester create form
    '''
    all_sems = Semester.objects.all()
    if request.method == 'POST':
        form = SemesterForm(request.POST)
        if form.is_valid():
            semster = form.save(commit=False)
            semster.created_by = request.user
            semster.save()
            return redirect('academics:all_semester')
    form = SemesterForm()
    ctx = {
        'all_sems': all_sems,
        'form': form,
    }
    return render(request, 'academics/all_semester.html', ctx)


@user_passes_test(user_is_staff)
def academic_session(request):
    '''
    Responsible for academic session list view
    and academic session create view.
    '''
    if request.method == 'POST':
        form = AcademicSessionForm(request.POST)
        if form.is_valid():
            ac_session = form.save(commit=False)
            ac_session.created_by = request.user
            ac_session.save()
            return redirect('academics:academic_sessions')
    else:
        form = AcademicSessionForm()
    all_academic_session = AcademicSession.objects.all()
    ctx = {
        'form': form,
        'academic_sessions': all_academic_session,
    }
    return render(request, 'academics/academic_sessions.html', ctx)


@user_passes_test(user_is_staff)
def departments(request):
    '''
    Responsible for department list view
    and department create view.
    '''
    if request.method == 'POST':
        form = DepartmentForm(request.POST)
        if form.is_valid():
            dept = form.save(commit=False)
            dept.created_by = request.user
            dept.save()
            return redirect('academics:departments')
    else:
        form = DepartmentForm()
    all_department = Department.objects.all()
    ctx = {
        'form': form,
        'departments': all_department,
    }
    return render(request, 'academics/departments.html', ctx)


@user_passes_test(user_is_staff)
def delete_semester(request, pk):
    obj = get_object_or_404(Semester, pk=pk)
    obj.delete()
    return redirect('academics:departments')


class UpdateDepartment(UpdateView):
    model = Department
    form_class = DepartmentForm
    template_name = 'academics/update_department.html'
    success_url = reverse_lazy('academics:departments')

    def form_valid(self, form):
        return super().form_valid(form)


@user_passes_test(user_is_staff)
def delete_department(request, pk):
    obj = get_object_or_404(Department, pk=pk)
    obj.delete()
    return redirect('academics:departments')

templates/academics/academic_sessions.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
<div class="row">
    <!-- SEMESTER LIST -->
    <div class="col-md-9">
        <table class="table border">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">学术会议</th>
                </tr>
            </thead>
            <tbody>
                {% for academic_session in academic_sessions %}
                <tr>
                    <td>{{ academic_session }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- SIDEBAR -->
    <div class="col-md-3">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="" data-toggle="modal" data-target="#exampleModal">添加新会议</a>
            </li>
            <!-- Add Department Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">添加新会议</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div> <!-- /modal header -->
                        <div class="modal-body">
                            <form action="" method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-outline-info float-right">
                                    创建会议
                                </button>
                            </form>
                        </div>
                        <!-- /modal body -->
                    </div>
                </div>
            </div>
        </ul>
    </div> <!-- /sidebar -->
</div>
{% endblock %}

templates/academics/accounts_list.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
<div class="row">
    <!-- ACCOUNTS LIST -->
    <div class="col-md-9">
        <table class="table border">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Username</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Role</th>
                </tr>
            </thead>
            <tbody>
                {% for account in accounts %}
                <tr>
                    <td>{{ account.username }}</td>
                    <td>{{ account.first_name }}</td>
                    <td>{{ account.email }}</td>
                    <td>
                        {% for group in account.groups.all %}
                            <span class="badge badge-dark">
                                {{ group }}
                            </span>
                        {% empty %}
                            general user
                        {% endfor %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- SIDEBAR -->
    <div class="col-md-3">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="{% url 'admin_tools:add_user' %}">添加用户</a>
            </li>
        </ul>
    </div> <!-- /sidebar -->
</div>
{% endblock %}

templates/academics/add_user.html
{% extends 'dashboard.html' %} 
{% load crispy_forms_tags %} 

{% block dashboard-body %}
<form action="." method="post" class="admission-form d-block">
    {% csrf_token %}
    <div class="row align-items-end">
      <div class="col-6">
        <h5>用户信息</h5>
        {{ user_form|crispy }}
        <h5>Permision</h5>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="user_role" id="admin-user" value="admin">
            <label class="form-check-label" for="admin-user">
                管理员用户
            </label>
        </div>
        <div class="form-check">
            <input class="form-check-input" type="radio" name="user_role" id="stuff-user" value="stuff">
            <label class="form-check-label" for="stuff-user">
                教职工用户
            </label>
        </div>
      </div>
    </div>
    <button type="submit" class="btn btn-primary">添加用户</button>
</form>
{% endblock %}

templates/academics/all_semester.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
<div class="row">
  <!-- SEMESTER LIST -->
  <div class="col-md-9">
    <table class="table border">
      <thead class="thead-dark">
        <tr>
          <th scope="col">学期</th>
          <th scope="col">班主任老师</th>
        </tr>
      </thead>
      <tbody>
        {% for semester in all_sems %}
        <tr>
          <td>{{ semester }}</td>
          <td>{{ semester.guide.name }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- SIDEBAR -->
  <div class="col-md-3">
    <ul class="list-group">
      <li class="list-group-item">
        <a href="" data-toggle="modal" data-target="#exampleModal">增加新学期</a>
      </li>
      <!-- Add Semester Modal -->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">增加新学期</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div> <!-- /modal header -->
            <div class="modal-body">
              <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-outline-info float-right">增加新学期</button>
              </form>
            </div>
            <!-- /modal body -->
          </div>
        </div>
      </div>
    </ul>
  </div> <!-- /sidebar -->
</div>
{% endblock %}

templates/academics/departments.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
<div class="row">
    <!-- SEMESTER LIST -->
    <div class="col-md-9">
        <table class="table border">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">Department</th>
                    <th scope="col">Dept. Code</th>
                    <th scope="col">Dept. Head</th>
                    <th scope="col">Dept. Creator</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for department in departments %}
                <tr>
                    <td>{{ department.name }}</td>
                    <td>{{ department.dept_code }}</td>
                    <td>{{ department.head.name }}</td>
                    <td>{{ department.created_by }}</td>
                    <td>
                        <a class="btn btn-sm btn-danger" href="{% url 'academics:delete_dept' pk=department.id %}">
                            删除
                        </a>
                        <a href="{% url 'academics:update_department' pk=department.pk %}" class="btn btn-sm btn-primary">
                            更新
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- SIDEBAR -->
    <div class="col-md-3">
        <ul class="list-group">
            <li class="list-group-item">
                <a href="" data-toggle="modal" data-target="#exampleModal">添加新部门</a>
            </li>
            <!-- Add Department Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">添加新部门</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div> <!-- /modal header -->
                        <div class="modal-body">
                            <form action="" method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-outline-info float-right">
                                    添加新部门
                                </button>
                            </form>
                        </div>
                        <!-- /modal body -->
                    </div>
                </div>
            </div>
        </ul>
    </div> <!-- /sidebar -->
</div>
{% endblock %}

templates/academics/permission_required.html
{% extends 'dashboard.html' %}

{% block dashboard-body %}
<div class="alert alert-warning">
    你没有权限进行此操作,<strong>请联系管理员</strong>.
</div>
{% endblock %}

templates/academics/update_department.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-body %}
<div class="row">
    <div class="col-md-12">
        <form action="." method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" value="更新" class="btn btn-success">
        </form>
    </div>
</div>
{% endblock %}