account/urls.py
from django.urls import path, include
from . import views


app_name = 'account'

urlpatterns = [
    path('', views.home, name='home'),
    path('auth/', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from account.views import dashboard

admin.site.site_header = "管理系统"
admin.site.site_title = "管理系统"
admin.site.index_title = "欢迎来到管理系统"

urlpatterns = [
    path('__debug__', include(debug_toolbar.urls)),
    path('admin/', admin.site.urls),
    path('', dashboard, name='index'),
    path('dashboard/', dashboard, name='index_view'),
    path('account/', include('account.urls')),
    path('academics/', include('academics.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('result/', include('result.urls')),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password/password_reset.html'
         ),
         name="password_reset",
         ),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='account/password/password_reset_done.html'
         ),
         name="password_reset_done",
         ),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password/password_reset_confirm.html'
         ),
         name='password_reset_confirm',
         ),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='account/password/password-reset-complete.html'
         ),
         name='password_reset_complete'
         ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='landing'),
    path('admission/', views.online_admission, name='online_admission'),
    path('admission/payment/<int:pk>/', views.online_admission_payment,
         name='online_admission_payment'),
    path('admission/paynow/<int:pk>/', views.payment,
         name='payment'),
]

result/urls.py
from django.urls import path

from . import views
from students.views import student_result_view

app_name = 'result'

urlpatterns = [
    path('<int:student_id>/<int:semester>/', student_result_view, name='show_result'),
    path('details/<int:student_id>/<int:semester>/',
        views.show_result_by_semester, name='result_by_semester'),
    path('upload-subjects-csv/', views.upload_subjects_csv, name='import_subject_csv'),
]

students/urls.py
from django.urls import path
from . import views

app_name = 'students'

urlpatterns = [
     path('', views.students_dashboard_index, 
          name='students_dashboard_index'),
     path('all/', views.students_view, name='all_student'),
     path('add/', views.add_student_view, name='add_student'),
     path('add-counsel-data/<int:student_id>/', views.add_counseling_data, 
          name='add_counseling_data'),
     path('admitted-students/', views.admitted_students_list,
          name='admitted_student_list'),
     path('online-applicants/', views.online_applicants_list, 
          name='online_applicants_list'),
     path('online-applicants/<int:pk>/admit/', views.admit_student,
          name='admit_student'),
     path('paid-registrants/', views.paid_registrants, 
          name='paid_registrants'),
     path('update-registrant/<int:pk>/', views.update_online_registrant, 
          name='update_online_registrant'),
     path('update/<int:pk>/', views.student_update_view.as_view(),
          name='update_student'),
     path('<int:pk>/detail/', views.student_detail_view.as_view(),
          name='student_details'),
     path('<int:pk>/delete/', views.student_delete_view, name='delete_student'),
     path('<int:pk>/students/', views.students_by_department_view,
          name='students_by_dept'),
     path('result/', views.student_result_view, name='result'),
     path('add_result_from_student/<int:pk>/', views.add_result_from_student_detail_view, 
          name='add_result_in_details'),
]

teachers/urls.py
from django.urls import path
from . import views


app_name = 'teachers'

urlpatterns = [
    path('all/', views.teachers_view, name='all_teacher'),
    path('add/', views.add_teacher_view, name='add_teacher'),
    path('<int:pk>/details/', views.teacher_detail_view, name='teacher_details'),
    path('<int:pk>/update/', views.teacher_update_view.as_view(),
         name='update_teacher'),
    path('<int:pk>/delete/', views.teacher_delete_view, name='delete_teacher'),
    path('designations/', views.designation_list_view.as_view(),
         name='designations'),
    path('create/designation/', views.create_designation,
         name='create_designation')
]

templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>SMS LIO DASHBOARD</title>
  <!-- FONT AWESOME KIT -->
  <script src="https://kit.fontawesome.com/16475baae0.js" crossorigin="anonymous"></script>
  <!-- GOOGLE FONT -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:400,700&display=swap" rel="stylesheet">
  <!-- BOOTSTRAP4 CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  {% block extra_header %}

  {% endblock %}
  <!-- CUSTOM CSS -->
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
  <link rel="icon" href="{% static 'images/favicon.png' %}">
</head>

<body class="bg-light">

  <section id="dashboard">
    <div class="container-fluid">
      <div class="dashboard-container row">
        <!-- START SIDENAV -->
        <div class="col-12 col-sm-12 col-md-4 col-lg-2 sidenav">
          <div class="logo">
            <!-- <img src="{% static 'images/logo.png' %}" alt="">-->
            <h4>管 理 系 统</h4>
          </div>
          <div class="sn-group">
            <a href="{% url 'account:dashboard' %}" class="sn-link dash-home">
              <i class="fas fa-tachometer-alt"></i>总计显示
            </a>
{#            <a class="sn-link dash-home" href="{% url 'pages:landing' %}" target="_blank">#}
{#              <i class="fas fa-globe-asia"></i>Visit Site#}
{#            </a>#}
          </div>
          <div class="sn-group">
            <h5>导入</h5>
            <nav>
              <a class="sn-link" href="{% url 'result:import_subject_csv' %}">
                <i class="fas fa-book"></i>导入学生信息
              </a>
            </nav>
          </div>
          <div class="sn-group">
            <h5>
              <a class="text-light" href="{% url 'students:students_dashboard_index' %}">
                学生
              </a>
            </h5>
            <nav>
              <a class="sn-link" href="{% url 'students:add_student' %}">
                <i class="fas fa-user-plus"></i>admission
              </a>
              <a href="" class="sn-link">
                <i class="fas fa-id-card-alt"></i>promotion
              </a>
              <a href="{% url 'students:all_student' %}" class="sn-link">
                <i class="fas fa-th-list"></i>all student
              </a>
              <a href="{% url 'students:result' %}" class="sn-link">
                <i class="fas fa-poll"></i>result
              </a>
            </nav>
          </div>
          <div class="sn-group">
            <h5>teacher</h5>
            <nav>
              <a class="sn-link" href="{% url 'teachers:add_teacher' %}">
                <i class="fas fa-user-tie"></i>new teacher
              </a>
              <a href="" class="sn-link">
                <i class="fas fa-id-card-alt"></i>promotion</a>
              <a href="{% url 'teachers:all_teacher' %}" class="sn-link">
                <i class="fas fa-th-list"></i>teachers
              </a>
              <a href="{% url 'teachers:create_designation' %}" class="sn-link">
                <i class="fas fa-th-list"></i>designation
              </a>
            </nav>
          </div>
          <div class="sn-group">
            <h5>departments</h5>
            <nav>
              <a class="sn-link" href="{% url 'academics:departments' %}">
                <i class="fas fa-plus"></i>departments
              </a>
              <a href="" class="sn-link">
                <i class="fas fa-plus"></i>new combination
              </a>
              <a href="{% url 'academics:academic_sessions' %}" class="sn-link">
                <i class="fas fa-plus"></i>academic sessions
              </a>
              <a href="" class="sn-link"><i class="fas fa-plus"></i>combinations</a>
              <a href="" class="sn-link"><i class="fas fa-plus"></i>subject set</a>
              <a href="{% url 'academics:all_semester' %}" class="sn-link">
                <i class="fas fa-plus"></i>semesters
              </a>
            </nav>
          </div>
          <div class="sn-group">
            <h5>Academic options</h5>
            <nav>
              {% if perms.auth.add_user %}
              <a href="{% url 'academics:add_user' %}" class="sn-link">
                <i class="fas fa-plus"></i>add new user
              </a>
              {% endif %}
              <a href="{% url 'academics:all_accounts' %}" class="sn-link">
                <i class="fas fa-plus"></i>all users
              </a>
            </nav>
          </div>
        </div>
        <!-- END OF SIDENAV -->

        <!-- START DASHBOARD BODY -->
        <div class="col-12 col-sm-12 col-md-8 col-lg-10 px-0 dashbody">
          <!-- NAVIGATION TOP -->
          <nav class="navbar navbar-expand-lg navbar-light bg-light shadow py-3 px-5">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
              aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
              <form id="searchForm" class="form-inline">
                <input class="form-control" type="search" placeholder="Search for..." aria-label="Search">
                <button id="searchBtn" class="btn lio-primary-bg my-2 my-sm-0" type="submit"><i
                    class="fas fa-search"></i></button>
              </form>
              <div class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                    aria-expanded="false"><i class="fas fa-user-circle fa-lg"></i></a>
                  <div class="dropdown-menu">
                    <a class="dropdown-item" href="#">Settings</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'account:logout' %}">
                      Logout {{ user.username }}
                    </a>
                  </div>
                </li>
              </div>
            </div>
          </nav>
          <!-- END NAV TOP -->

          <div id="dash-body-inner" class="container-fluid p-5">

            {% block dashboard-body %}

            <!-- top stat row -->
            <div class="row m-0 p-0">
              <h3 class="mb-3">Dashboard</h3>
              <div class="col-12 p-0">
                <div class="topstat d-flex justify-content-between">
                  <div class="statbox">
                    <i class="fas fa-users fa-3x"></i>
                    <div class="text">
                      <p>students</p>
                      <h3>{{ total_students }}</h3>
                    </div>
                  </div>
                  <div class="statbox">
                    <i class="fas fa-users fa-3x"></i>
                    <div class="text">
                      <p>teachers</p>
                      <h3>{{ total_teachers }}</h3>
                    </div>
                  </div>
                  <div class="statbox">
                    <i class="fas fa-users fa-3x"></i>
                    <div class="text">
                      <p>clubs</p>
                      <h3>20</h3>
                    </div>
                  </div>
                  <div class="statbox">
                    <i class="fas fa-users fa-3x"></i>
                    <div class="text">
                      <p>books</p>
                      <h3>2000</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <!-- second row -->
            <div id="second-row" class="row m-0 p-0">
              <div class="col-12 mt-5 p-0 d-flex justify-content-between">
                <div class="card">
                  <div class="card-header">
                    <h5>upcoming events</h5>
                  </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between">
                      <span class="name">Seminar on Machine Learning</span>
                      <span class="date">december 12</span>
                      <span class="organizer">dpi decoder</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                      <span class="name">Spelling Bee</span>
                      <span class="date">november 26</span>
                      <span class="organizer">english club</span>
                    </li>
                    <li class="list-group-item d-flex justify-content-between">
                      <span class="name">hello! you.</span>
                      <span class="date">december 2</span>
                      <span class="organizer">cultural club</span>
                    </li>
                  </ul>
                </div>
                <div class="card">
                  <div class="card-header">
                    <h5>Notice Board</h5>
                  </div>
                  <ul class="list-group">
                    <li class="list-group-item">
                      <h5 class="date">23 nov 2019</h5>
                      <h5>Admit card collecting notice.</h5>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <!-- end of second row -->

            <!-- payment row -->
            <div class="row m-0 p-0">
              <h3 class="mt-5 mb-3">Stuff Payment</h3>
              <div class="col-12 p-0 d-flex justify-content-between">
                <div class="unpaid card">
                  <ul class="list-group list-group-flush">
                    <li class="title list-group-item d-flex justify-content-between">
                      <h5>unpaid</h5>
                        <a href="" title="Mark as paid">
                          <i class="far fa-check-circle"></i>
                        </a>
                    </li>
                    <li class="list-group-item">
                      <input type="checkbox" name="paid"> Md. Shariful Islam
                    </li>
                    <li class="list-group-item">
                      <input type="checkbox" name="paid"> Md. Shariful Islam
                    </li>
                    <li class="list-group-item">
                      <input type="checkbox" name="paid"> Md. Shariful Islam
                    </li>
                  </ul>
                </div>
                <div class="paid card">
                  <ul class="list-group list-group-flush">
                    <li class="title list-group-item">
                      <h5>paid</h5>
                    </li>
                    <li class="list-group-item">Soma rani das</li>
                    <li class="list-group-item">Johir chy</li>
                  </ul>
                </div>
              </div>
            </div>

            {% endblock dashboard-body %}

          </div>
          <!-- <footer id="footer">
            <div class="container">
              <div class="row">
                <div class="col-12 py-1">
                  <p>&copy;copyright 2020, reserved by <em>pidevs</em></p>
                </div>
              </div>
            </div>
          </footer> -->
        </div>
        <!-- END DASHBOARD BODY -->
      </div> <!-- dashboard container fluid -->

    </div>
  </section>

  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
  crossorigin="anonymous"></script>
  {% block extrajs %}
  {% endblock %}
</body>

</html>

templates/index.html
{% extends 'layout.html' %}
{% block title %}
    管理系统
{% endblock %}

{% block content%}
<!-- Home Hero Section -->
<section id="home-hero">
  <div id="home-hero--inner">
    <div class="container">
      <div class="row py-5 justify-content-center align-items-center">
        <div class="col-12 py-5 text-center">
          <h1>Daffodil Polytechnic Institute</h1>
          <h5><em>Boost your knowledge and gain career</em></h5>
        </div>
      </div>
    </div>
  </div>
</section>


{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %} {% endblock %}
  </title>
  <!-- FONT AWESOME KIT -->
  <script src="https://kit.fontawesome.com/16475baae0.js" crossorigin="anonymous"></script>
  <!-- GOOGLE FONT -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:400,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  
  {% block headrefs %}
    
  {% endblock headrefs %}
    
</head>

<body>

    <nav name="header" class="navbar navbar-default" role="navigation" style="background-color: #3c9cfd">
{#        <img src="{% static "/images/logo.png" %}"  />#}
        <div class="logo">
            <a style="font-family: 'Consolas', 'Deja Vu Sans Mono', 'Bitstream Vera Sans Mono', monospace;color: white;font-size: large" href="#">用户系统</a>
        </div>
    </nav>
  <!-- SITE BODY -->
  {% block content %}
  {% endblock %}
  <!--SITE BODT END-->


  <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>

  
  {% block extrajs %}
    
  {% endblock extrajs %}

</body>

</html>